### ISSUE TITLE
Got 500 when signing up with my github account

### ISSUE THREAD

**Issue by jpgbarbosa** [whitesmith/hawkpost#129]

**Comment by dethos** [comment]
@jpbarbosa can you confirm that this is still happening?

**Comment by jpgbarbosa** [comment]
Yup @dethos

**Comment by dethos** [comment]
This seems to happen when a user already has an account (not a social one) and tries to login with github. The issue might reside on the library used (django-allauth: https://github.com/pennersr/django-allauth/issues/520#issuecomment-250747105), I will try to understand if it will be fixed there, before implementing a solution that works around it.

**Comment by dethos** [comment]
This issue should be fixed now. The remaining design issues will be discussed and handled in #230.
