### ISSUE TITLE
Stylesheets take more than a second to load

### ISSUE THREAD

**Issue by pjaneiro** [whitesmith/hawkpost#138]
![image](https://cloud.githubusercontent.com/assets/4594879/18532988/a6f55290-7ad7-11e6-9837-7c85c28280c8.png)

In every page I've visited so far, the file style.<hash>.css takes a lot to load, and the file sepia.htc doesn't load at all. I don't know if both events are related in any way, but at least the first one may be a problem

**Comment by dethos** [comment]
@Budgerous is this still happening?

**Comment by pjaneiro** [comment]
Nope. Will close it
