### ISSUE TITLE
Cannot delete account when signed-on via github.

### ISSUE THREAD

**Issue by techhazard** [whitesmith/hawkpost#183]
I logged in with github SSO which went very well.

After trying to add my key which didn't work (fingerprint kept mismatching, and key is invalid error. This could be my fault),
I wanted to delete my account.

I clicked on the `Do you wish to delete your account? if yes, just click here` link on the settings page.

I then was asked for my password which, obviously, I hadn't need to set.

and without a password I can't delete my account...

Could this be fixed?

**Comment by dethos** [comment]
@awesomefireduck Yes, that definitely needs to be fixed. 
For now if you want to delete your account a possible workaround would be: 
- Logout
- Reset Password
- Add new password
- Then login and delete your account

**Comment by entrepreneurj** [comment]
Hi, just checking, would it be as simple as allowing the account deletion to go ahead if there is no password set?

**Comment by dethos** [comment]
@entrepreneurj not sure yet, probably we would like to add some kind of validation. 
But more feedback would be nice, so we can better define what really needs to be done.

**Comment by ghost** [comment]
password reset 
it may pull reuest
