### ISSUE TITLE
Focus issue in settings page

### ISSUE THREAD

**Issue by techhazard** [whitesmith/hawkpost#184]
The focus automagically jump to the `First name:` field whenever the mouse button is released.

To be able to paste e.g. a key, I need to hold the mouse button in that input field while pressing the paste shortcut. Otherwise it will paste in the `First name:` field.

This is annoying to the point of being unusable.

I'm using Safari Version 9.1.3 (11601.7.8) on Mac OSX El Capitain 10.11.6 (15G1004)

**Comment by dethos** [comment]
@awesomefireduck can you verify if this issue is still happening to you? It should be fixed by now (since #200 was merged today)

**Comment by techhazard** [comment]
This seems fixed, thanks!
