### ISSUE TITLE
Password reset fields inconsistency

### ISSUE THREAD

**Issue by techhazard** [whitesmith/hawkpost#193]
When resetting my password I clicked the reset link in the email I got.

The form to change the password has two input fields: password and password-confirm.

Above the password field there is the text: `Insert new password:`
Above the password-confirm field there is the text: `Insert new password (again):`

In both fields as a `placeholder` there is the text: `Current password`.
This is confusing. (above all because I have no "Current" password due to github SSO, see #183 )

I suggest those be changed to `New password` and `New password (confirm)` or something along those lines

**Comment by dethos** [comment]
@awesomefireduck the issue should be solved now. Please try again and let us know if everything went as expected.
