### ISSUE TITLE
Provide Hawkpost fingerprint on web site

### ISSUE THREAD

**Issue by drohm** [whitesmith/hawkpost#205]
Shouldn't the official Hawkpost public key fingerprint be shown on the web site so that we can confidently verify the key we're adding to our local keystore is, in fact, the offical public key for Hawkpost?

**Comment by dethos** [comment]
@drohm yes, just noticed that the link that on the `help` page is empty. Also there should be a link on the settings page.

I will fix the issue as soon as possible. For now you can check the key [here](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0A9A952091306C6A)

**Comment by dethos** [comment]
This issue should be solved now. Will close until further notice.
