### ISSUE TITLE
Have invites available for Keybase

### ISSUE THREAD

**Issue by drohm** [whitesmith/hawkpost#206]
If Hawkpost would like an invite to Keybase, please let me know and I'll send you one.

https://keybase.io

**Comment by dethos** [comment]
@drohm thanks for your suggestion. 
We also use keybase.io and still have here an invite reserved for hawkpost, just in case. For now hawkpost's public key was upload to a [regular keyserver](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0A9A952091306C6A) and the use of keybase is still being discussed.
