### ISSUE TITLE
Sign in with Github button is acting as regular login button

### ISSUE THREAD

**Issue by ruimagalhaes** [whitesmith/hawkpost#225]
When I try to login with Github it asks me to input credentials on the fields

**Comment by beatrizbeato** [comment]
http://recordit.co/9TO2X0i4PK

**Comment by dethos** [comment]
@ruimagalhaes @beatrizbeato This issue should be fixed now and will be closed. Please check when you have the time.

**Comment by beatrizbeato** [comment]
yup, works fine for me now 👍
