### ISSUE TITLE
Login modal blurs when hovering a button/link

### ISSUE THREAD

**Issue by ggraca** [whitesmith/hawkpost#226]
In chrome, with devtools open, I get a strange blur in the login modal. It might have to do with screen size change.

**Comment by dethos** [comment]
@GGraca can you show us an example (screenshot / video)? or detail a little better your description?

**Comment by agrancho** [comment]
@dethos found it too and shot a video of it:
http://recordit.co/APbyEXFPQ7

**Comment by dethos** [comment]
The effects were already removed (not fixed), but since a new UI is planned we will not address this issue.
