### ISSUE TITLE
Social signup when email already exists

### ISSUE THREAD

**Issue by dethos** [whitesmith/hawkpost#230]
The templates for this feature are not implemented. A simple blank page with a form is presented to the user. Our page structure and styles should be applied to these pages as well.

**Comment by pdcribeiro** [comment]
How can I reproduce this issue? I tried signing in with github after creating an account with the same email but got the usual styled page.

**Comment by dethos** [comment]
@pdcribeiro 

![Screenshot](https://user-images.githubusercontent.com/887454/99833846-91512f80-2b5a-11eb-9a1b-38167395f1c4.png)

Steps: 
1. Create account with email address
2. Confirm email and make sure the account is active
3. Log out
4. Sign in with Github (Github account email address must be the one used on step 1 )
