### ISSUE TITLE
Settings save button overlaps language field.

### ISSUE THREAD

**Issue by mmachado95** [whitesmith/hawkpost#245]
<img width="1440" alt="screen shot 2017-08-11 at 15 32 02" src="https://user-images.githubusercontent.com/11708251/29217816-b942a7fe-7eaa-11e7-8b57-0d364a6d3ac5.png">

**Comment by dethos** [comment]
@Kabombom thanks for the report. Can you tell us which browser (and version) were you using when this happened?

**Comment by mmachado95** [comment]
```
Browser: Google Chrome
Version: 60.0.3112.101
```

**Comment by nunosilva800** [comment]
Seems to happen on screens with width < 1280px
