### ISSUE TITLE
Please Help - Unable to Get Email Working (Gmail/SMTP Possible?)

### ISSUE THREAD

**Issue by dohlin** [whitesmith/hawkpost#249]
Hey guys,

So after eventually getting Hawkpost up and running on a fresh Ubuntu 16.04 installation, I'm having major troubles getting email to work for when a new user signs up.

Being a small, simple, self hosted setup, I'd like to just use Gmail SMTP if possible as that's what every other service I run uses and I find it easiest for me personally.  I'm not sure if that's not possible or if it's somehow evading me.

I couldn't find anything hawkpost specific, so I've Google'd till I'm blue in the face, and in my .env file I started off with a basic configuration based on guidelines I've found:

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '[redacted - my gmail address]'
EMAIL_HOST_PASSWORD = '[redacted - gmail app password]'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```

However, this throws the following error along with a long stack trace:

> smtplib.SMTPSenderRefused: (530, b'5.7.0 Must issue a STARTTLS command first. e18sm653160qtc.59 - gsmtp', '[redacted - my gmail address]')

If I try changing the port to 465 and instead of "EMAIL_USE_TLS = True" I use "EMAIL_USE_SSL = True" then I get the following error after a long pause (again with a long stack trace):

> smtplib.SMTPServerDisconnected: Connection unexpectedly closed

I've tried many, many other varying combinations of lines with and without the single quotes, changing the "EMAIL_BACKEND" to 'django_smtp_ssl.SSLEmailBackend', leaving that line out entirely (which throws a 

> Gets: IndexError: string index out of range

error , etc. etc. etc. but nothing has resulted in successful sending of emails.

I would sincerely appreciate any help or guidance anyone could provide, as I'd really really like to get this working if at all possible.  Thank you!!

**Comment by dethos** [comment]
hey @dohlin 

Assuming you are using the `production` settings, you shouldn't need to set `EMAIL_BACKEND` since that one is the default. As far as I know the port 465 and `EMAIL_USE_TLS` should work fine for the gmail smtp server.

Do you have 2-factor authentication active in your Google account? If Yes, you might have to create an application specific password in order to be able to connect to the smtp server. ([here](https://security.google.com/settings/u/1/security/apppasswords))

**Comment by dohlin** [comment]
@dethos Yes I do have 2FA enabled, but I'm already using an app password I generated specifically for this so no issues there.

Thanks for the heads up on the email_backend piece, I didn't realize that.  However I don't think I'm using the production settings as when I first start the server using 

> python manage.py runserver 0.0.0.0:8000

I see a line that says "Django version 1.11.5, using settings 'hawkpost.settings.development'".  I'm assuming that means I'm using some dev settings --- I'm sorry as I know this is going to be a stupid question, but how would I switch to using the production settings?  I followed the guide in the readme as close as possible and while I had to fill in a couple details on my own, I don't think I changed or set anything to use development settings by default.  Thank you for your help!

**Comment by dohlin** [comment]
@dethos EDIT: So I did some further digging and messing with things, and while I still can't figure out why Gmail won't work, I can successfully send through a postfix server that relays to Gmail instead, so that's sufficient for me in this case.

So if you could just give me instructions on how to change over to using the "production" settings instead of development I'd be extremely grateful.  I tried changing the "hawkpost.development" line in manage.py to "hawkpost.production" but that definitely broke things, lol.  Sorry, I realize this is probably a super noob question but I am learning a lot so thank you!

**Comment by dethos** [comment]
@dohlin the readme file / documentation is really lacking on that issue. That is something we have to improve as soon as we can (it is scheduled for the next few weeks) . 

To deploy with the `production` settings you just have to setup the environment variable `HAWKPOST_ENV` to `production`. It is the same thing that you just did manually. 

Certain things "broke" because the production settings require:

* An HTTPS connection, Hawkpost is expected to be deployed behind a server (for example `nginx`) that will handle TLS.
* You will need to setup the `SITE_DOMAIN` environment variable, because it will only serve requests that use that domain.

**Comment by dohlin** [comment]
Ok so first of all just wanted to say thank you again for all the additional information you're providing me, as  trying to find this stuff has proven difficult.

So, I actually do have an Apache reverse proxy server set up in exactly that fashion - in front of this server, proxying requests, and taking care of HTTPS with a LE cert.


At this point I seem to have narrowed things down to the setting of "Debug = False" in the "production.py" file within the "settings" folder.  I can run in "production" settings if I change this to "Debug = True" everything works, but when it's 'false' then I get a

> "GET / HTTP/1.1" 500 27

error in the console on the server, and a "Server Error 500" error when attempting to visit the site by the URL I have set up.  I should note that I have SITE_DOMAIN and ALLOWED_HOSTS set to just 'hawkpost.example.com'.  


So at this point I'd like to clarify a couple questions:

1). When you say that the production settings require an HTTPS connection, do you mean just an internet-facing HTTPS connection?  Or does the Hawkpost server itself need to be using SSL (self signed or whatever) too?  Because right now my main webserver that proxies traffic to my hawkpost server handles the HTTPS side of things via that LE cert, but traffic on my LAN between the two servers is HTTP.  Would that be causing the symptoms I'm seeing?

and 2).  I noticed the same "development" setting set in hawkpost/hawkpost/celery.py...should I be changing this one to "production" too or not?


EDIT1: I figured out the proper syntax for multiple "ALLOWED_HOSTS" as eventually I want to make that work.  I'm not currently using this just to make things as simple as possible for troubleshooting the issues I'm seeing, but In case anyone finds themselves the same boat I was in, it's:

> ALLOWED_HOSTS=hawkpost.example1.com,hawkpost.example2.com


EDIT2: Ok, I think I'm finally getting somewhere.  With debug set to false, and enabling logging by putting

`LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/dave/hawkpost/mysite.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}` 

in my "production.py" file, I get the following log:

`[24/Sep/2017 15:22:59] ERROR [django.request:135] Internal Server Error: /
Traceback (most recent call last):
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/dave/hawkpostvenv/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'css/style.css'
[24/Sep/2017 15:22:59] ERROR [django.server:124] "GET / HTTP/1.1" 500 27`

Does this help in pin pointing the issue here at all?  Thank you!!


EDIT3: I think I finally got it!

On a whim, per https://stackoverflow.com/questions/44160666/valueerror-missing-staticfiles-manifest-entry-for-favicon-ico I tried running "python manage.py collectstatic".  This was all with debug set to the default production value of 'False'.

After that completed, I suddenly was able to run "python manage.py runserver 0.0.0.0:8000" and access it from the "hawkpost.example.com" URL I had set up in "SITE_DOMAIN" and "ALLOWED_HOSTS" in my .env settings file.

The only thing I'm seeing now is, when I log in, I get the following error message in the Chrome browser console - is this to be expected or what is this saying?

```
Uncaught TypeError: Cannot read property 'querySelector' of null
 at modalEffects.13dd4778efc3.js:16

at modalEffects.13dd4778efc3.js:16

at Array.forEach (<anonymous>)
    
at init (modalEffects.13dd4778efc3.js:14)
    
at modalEffects.13dd4778efc3.js:56
    
at modalEffects.13dd4778efc3.js:57
```

Further testing in progress, but I'm hopeful!

FINAL EDIT: Welp, spoke too soon.  For some reason email verification emails I receive just fine, but I get no email when I attempt to put anything in a generated "box" and submit.  The following is the traceback I now get....no idea what's going on :(

https://pastebin.com/7yb3GHki

**Comment by dohlin** [comment]
I'm dumb :) I didn't have the celery workers command running in addition to the server itself.  A couple more errors I'm still seeing but unrelated to this ticket so closing this one as such :) Thanks!
