### ISSUE TITLE
Website does not seem to work

### ISSUE THREAD

**Issue by rorymbyrne** [whitesmith/hawkpost#259]
Accessing links and trying to send messages does not seem to do anything once Encrypt and Send is clicked.

**Comment by dethos** [comment]
Hello @rorymbyrne, can you tell us a little bit more about your setup (like operating system and browser) where this is happening? so we can try to reproduce the issue.

Also if there is any error on the console, can you add it here as well?

**Comment by dethos** [comment]
We did not received any confirmations or more details about the problem, so I will close the issue until then.
