### ISSUE TITLE
I can't deploy this project to heroku,

### ISSUE THREAD

**Issue by kumareshsaran** [whitesmith/hawkpost#270]
I am facing the same problem in deploying this project to Heroku.
below I attached the manage.py file

## If any one knows please ping me.

```
import os
import sys
import dotenv


if __name__ == "__main__":
    dotenv.read_dotenv()
    environment = os.environ.get("HAWKPOST_ENV", "development")
    os.environ.setdefault("DJANGO_SETTINGS_MODULE",
                          "hawkpost.settings.{}".format(environment))

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**Comment by dethos** [comment]
@kumareshsaran can you explain the problem with a little more detail? 
We need more data to be able to help. At the moment we don't have any instructions to deploy on Heroku (but we can add them, if there is enough interest).

**Comment by dethos** [comment]
Given the lack of response during the last ~3 months, I will close this PR. Meanwhile if any new information is added we can re-open it.
