### ISSUE TITLE
This key is not valid

### ISSUE THREAD

**Issue by chamalis** [whitesmith/hawkpost#272]
I have generated a PGP key using RSA, by:

    gpg --full-generate-key

I exported the key with:

    gpg --armor --export AC981DBEDA92F900

I am getting the following error messages:

![image](https://user-images.githubusercontent.com/908356/35403666-1adb6140-0209-11e8-8f57-b8ad9f5703e8.png)

**Comment by dethos** [comment]
@chefarov This might be an issue, I suspect your key is not being recognized as one. Could you try to add it with this format:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

[your current key present in the screenshot]

-----END PGP PUBLIC KEY BLOCK-----
```


and tell us if it worked.

**Comment by chamalis** [comment]
I would bet I had tried this before... but... anyway now it seems to work fine. Thank you
