### ISSUE TITLE
Recipient email does not appear in "Link no longer active" page

### ISSUE THREAD

**Issue by tomascarvalho** [whitesmith/hawkpost#282]
If we click a link that is no longer active (for example: https://hawkpost.co/box/78d09474-7ad8-42af-91d7-b95bd40798f6), the following recommendation is shown:

> In any of the above cases, you should contact the recipient ( ) in order to fix the issue.

When inspecting this element, it is seen that inside the parenthesis a mail should be displayed, which is not being shown.
Is this a bug?

**Comment by dethos** [comment]
Yes it is! Thanks for the info.
