### ISSUE TITLE
Dotenv Problem

### ISSUE THREAD

**Issue by AmeeruddinSd** [whitesmith/hawkpost#285]
![2018-10-05](https://user-images.githubusercontent.com/36222156/46551132-82fd1680-c8f4-11e8-8487-5cb3341b355a.png)

**Comment by AmeeruddinSd** [comment]
![2018-10-05 1](https://user-images.githubusercontent.com/36222156/46551472-7fb65a80-c8f5-11e8-9728-a05a1c2e3a81.png)

**Comment by tomascarvalho** [comment]
@ShamilSd Please do `pipenv install --dev` before running `pipenv run` commands. 
Also, create a `.env` file with the same contents of `.env.sample` and fill in the required values.

If it works for you please leave some feedback

**Comment by dethos** [comment]
Since @tomascarvalho is correct (based on the screenshots) and 19 when by without any new information, I will close this issue. If you need to further discuss it, feel free to post and I will re-open it.
