### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mzch** [whitesmith/hawkpost#292]
Hi,

I installed hawkpost and tried to sign-up using email but nothing happened.
And then tried to login using github, hawkpost said, "Server Error".
How can I fix this issue?

Python: 3.6.8
node.js: v10.16.0
OS: Debian GNU/Linux 10 (Buster)

**Comment by dethos** [comment]
Hi @mzch , 
which method did you use to install? 
Did you tried to login after you created the account using "email"?
Did you configure the SMTP server (in case the required email confirmation is active)?
Did you add your GitHub application credentials on the administration (in order to configure the social authentication mechanism)? This is required for the "login using github" functionality.

In order to be able to provide any help, I will need more details, such as the answers to the above questions and some logs or error output.

**Comment by mzch** [comment]
Hi @dethos 

1. I installed by cloning the repogitory.
1. Yes, but nothing happened
1. STMP server? No, but my localhost can mail to me.
1. Yes. But I put ```https://example.com/auth/complete/github``` as callback page. Right?

Well, using ```gulp build``` makes an error as below unless I do ```npm install```
```
[18:27:11] Local modules not found in ~
[18:27:11] Try running: npm install
```

**Comment by dethos** [comment]
>     2\. Yes, but nothing happened

No errors on the logs? (either on the server side and on the browser console)

**Comment by mzch** [comment]
Oh, browser console has errors as below:

```
POST https://sqzall.com/users/signup/ jquery-2.2.2.min.1d35678c5edb.js:4
500
send @ jquery-2.2.2.min.1d35678c5edb.js:4
ajax @ jquery-2.2.2.min.1d35678c5edb.js:4
(anonymous) @ authform.f2bf2819f8ac.js:35
dispatch @ jquery-2.2.2.min.1d35678c5edb.js:3
r.handle @ jquery-2.2.2.min.1d35678c5edb.js:3
authform.f2bf2819f8ac.js:44 

Uncaught TypeError: Cannot read property authform.f2bf2819f8ac.js:44
'form' of undefined
    at Object.<anonymous> (authform.f2bf2819f8ac.js:44)
    at i (jquery-2.2.2.min.1d35678c5edb.js:2)
    at Object.fireWith [as rejectWith] (jquery-2.2.2.min.1d35678c5edb.js:2)
    at z (jquery-2.2.2.min.1d35678c5edb.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.2.min.1d35678c5edb.js:4)
(anonymous) @ authform.f2bf2819f8ac.js:44
i @ jquery-2.2.2.min.1d35678c5edb.js:2
fireWith @ jquery-2.2.2.min.1d35678c5edb.js:2
z @ jquery-2.2.2.min.1d35678c5edb.js:4
(anonymous) @ jquery-2.2.2.min.1d35678c5edb.js:4
load (async)
send @ jquery-2.2.2.min.1d35678c5edb.js:4
ajax @ jquery-2.2.2.min.1d35678c5edb.js:4
(anonymous) @ authform.f2bf2819f8ac.js:35
dispatch @ jquery-2.2.2.min.1d35678c5edb.js:3
r.handle @ jquery-2.2.2.min.1d35678c5edb.js:3
```
p.s.

Use gunicorn and Apache. Does it have a problem?

**Comment by mzch** [comment]
I reinstalled hawkpost and modified mail settings, then could login successfully. Thanks.
