### ISSUE TITLE
Github callback URL?

### ISSUE THREAD

**Issue by mzch** [whitesmith/hawkpost#297]
**What URL should I set as a callback URL for Github login?**

**Comment by dethos** [comment]
@mzch Hawkpost uses `django-allauth`, which mean to configure Github login you can follow these steps:
* https://django-allauth.readthedocs.io/en/latest/providers.html#github

The call back should be: `http(s)://{YourDomain}/accounts/github/login/callback/`

**Comment by mzch** [comment]
I tried it but Hawkpost reported 'NOT FOUND'...
```
The page you are looking for, does not exist. Please check the URL to check you entered it correctly.
```

**Comment by dethos** [comment]
@mzch sorry about that, in fact we include the urls using

```python
url(r'^users/', include('allauth.urls')),
``` 

So it should be `http(s)://{YourDomain}/users/github/login/callback/`

**Comment by mzch** [comment]
Thanks @dethos , I tried but Hawkpost reported failure.
```
Social Network Login Failure
An error occurred while attempting to login via your social network account.
```
the result URL is below:
https://encsh.com/users/github/login/callback/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=z4oN5SFSH40y

Could you test [my instance](https://encsh.com/)?

**Comment by mzch** [comment]
Here are screenshots.
- Github settings:
![FireShot_Capture_011](https://user-images.githubusercontent.com/621178/68966599-d80e9a00-0821-11ea-8dd8-01940997f15d.png)
- Result
![FireShot_Capture_012](https://user-images.githubusercontent.com/621178/68966611-dfce3e80-0821-11ea-972e-5621a0ce49a6.png)

**Comment by dethos** [comment]
@mzch what does the server logs say?

Did you add the `SocialApp` record to the administration with your Github's application `client Id` and `client secret`?

**Comment by mzch** [comment]
For example,
```
95.172.183.111 - - [15/Nov/2019:10:41:59 -0800] "GET /users/github/login/?process=login HTTP/2.0" 302 433 "https://encsh.com/users/github/login/?process=login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
95.172.183.111 - - [15/Nov/2019:10:42:00 -0800] "GET /users/github/login/callback/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=hosP2K2Lf2eG HTTP/2.0" 200 347 "https://encsh.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
```
Yes, I did. Plz show below:
![FireShot_Capture_013](https://user-images.githubusercontent.com/621178/68968017-e4482680-0824-11ea-8508-60421568dfff.png)

**Comment by dethos** [comment]
Based on the log you provided, there seems to be a mismatch between the `redirect_uri` the app is providing and the URI you defined on Github's hub settings.

On your screenshot: you used `https://encsh.com/users/github/login/callback/` and your application is setting it as: `redirect_uri=http://encsh.com/users/github/login/callback/`.

More info here: https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/?redirect-uri-mismatch&state=IIgpHkBolgvG#redirect-uri-mismatch

Setting `ACCOUNT_DEFAULT_HTTP_PROTOCOL = ”https”` might fix your issue.

**Comment by mzch** [comment]
Oh, great!
I set `ACCOUNT_DEFAULT_HTTP_PROTOCOL="https"` in settings/production.py and suceeded!
Thanks @dethos !
It also worked out in a manner that is inserting `RequestHeader set X-Forwarded-Proto https` in apache conf file.
