### ISSUE TITLE
TLS Certificate of hawkpost.co expired 2 days ago

### ISSUE THREAD

**Issue by moritzruth** [whitesmith/hawkpost#304]

**Comment by dethos** [comment]
@moritzruth Thanks. 

At the moment I don't maintain the `hawkpost.co` instance, so I cannot solve the issue right away. @pjaneiro can you please take a look at this?

**Comment by pjaneiro** [comment]
Hey everyone. Sorry for this. Auto-update failed. Solved. Will be on the lookout for this
