### ISSUE TITLE
When importing the public key from a Keyserver URL fails, an error should be shown

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/hawkpost#31]
I accidentally entered this Keyserver URL:

```
http://pool.sks-keyservers.net/pks/lookup?op=vindex&search=0xAC1813EF59827D8B
```

Which is a `vindex` operation, instead of `get`.
I was informed that "Settings successfully updated", but the public key was not imported and I only noticed when I tried to create a box.

**Comment by dethos** [comment]
Yup, you are right, the validation is not working properly.
