### ISSUE TITLE
Fix simple typo: statments -> statements

### ISSUE THREAD

**Issue by timgates42** [whitesmith/hawkpost#313]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine boxes/tests.py.
2. Search for `statments`.

# Expected Behaviour

1. Should read `statements`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR.

https://github.com/timgates42/hawkpost/pull/new/bugfix_typo_statements

Thanks.

**Comment by dethos** [comment]
@timgates42 Thanks. I created a new PR from your fix.
