### ISSUE TITLE
Timezone is affecting Box expiration time?

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/hawkpost#32]
I'm on a GMT-3 timezone and when selecting the expiration date of a new box, I chose on the same day and 2 hours later.
I immediately tried to use the box, and it was already expired.

My guess is that the server is interpreting this date as a local time instead of accounting for the timezone.

**Comment by dethos** [comment]
Currently the project only handles the UTC timezone ([check here](https://github.com/whitesmith/hawkpost/blob/master/hawkpost/settings/common.py#L121)). Definitely we should improve in this area and support user defined timezones.
