### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by dethos** [whitesmith/hawkpost#41]
The purpose of this issue it to discuss the viability of implementing `integrations`. This is just an idea, so nothing official. The use case would be: a user using another application (chat, web or desktop app) could automatically generate boxes and retrieve/share the urls without the need to visit hawkpost website.

For this we would need to expose an API and have a way to track authorized applications. For desktop apps this would be rather simple but for other type of integrations could be quite complex.

**Comment by dethos** [comment]
A service that could be nice to integrate with, is keybase.

**Comment by j2kun** [comment]
For the record, I was able to get the settings to accept `https://keybase.io/j2kun/key.asc` but not `https://keybase.io/j2kun/` as the keyserver url. FWIW my browser cuts off the "suggested text" in that text field so it wasn't so easy for me to tell what the right url was.

I totally happy with this solution and ignoring full keybase integration, it just wasn't so easy to figure out what's the right url to copy/paste.
