### ISSUE TITLE
Build a roadmap. 

### ISSUE THREAD

**Issue by andrewhowdencom** [whitesmith/hawkpost#47]
Hi All, 

This looks like a super nice idea. It'd be good if there was some sort of roadmap so we can get an idea on when it gets to 1.0.0, after which we'll look it implementing it. Is there some list of tasks that block 1.0.0? 

Cheers,

**Comment by dethos** [comment]
Hi @andrewhowdencom, 

Completely agree with you here. 
Currently we are studying and planning the next steps, more precisely what features are really important for a first stable version and what needs to be done to make the project more solid (that will be the 1.0.0). 

Soon the proposed "roadmap" will be posted on the wiki and the project milestones added to the issue tracker. I will mark this issue as discussion, so we can receive input from anyone interested on the matter.

Cheers

**Comment by dethos** [comment]
[Here](https://github.com/whitesmith/hawkpost/wiki/Roadmap) is an overview of what we have planned/in discussion for the next months.

**Comment by andrewhowdencom** [comment]
This is amazing! Thank you very much, my colleagues and I are most excited.
